/* SPDX-License-Identifier: GPL-2.0-only */
#ifndef IPU4P_ISYS_CSI2_REGS_H
#define IPU4P_ISYS_CSI2_REGS_H

#include <linux/bits.h>

#define IPU4P_CSI2_VC_COUNT				4U

/* ISYS UNISPART and SIP interrupt registers */
#define IPU4P_ISYS_UNISPART_IRQ_EDGE			0x7c000
#define IPU4P_ISYS_UNISPART_IRQ_MASK			0x7c004
#define IPU4P_ISYS_UNISPART_IRQ_STATUS			0x7c008
#define IPU4P_ISYS_UNISPART_IRQ_CLEAR			0x7c00c
#define IPU4P_ISYS_UNISPART_IRQ_ENABLE			0x7c010
#define IPU4P_ISYS_UNISPART_IRQ_LEVEL_NOT_PULSE		0x7c014
#define IPU4P_ISYS_UNISPART_SW_IRQ_REG			0x7c414
#define IPU4P_ISYS_UNISPART_SW_IRQ_MUX_REG		0x7c418
#define IPU4P_ISYS_UNISPART_IRQ_SW			BIT(22)
#define IPU4P_ISYS_UNISPART_IRQ_CSI2(port)		((port) ? BIT(4) : BIT(3))
#define IPU4P_ISYS_ISA_ACC_IRQ_CTRL_BASE		0xb0c00
#define IPU4P_ISYS_A_IRQ_CTRL_BASE			0xbe200
#define IPU4P_ISYS_SIP0_IRQ_CTRL_BASE			0x66d00
#define IPU4P_ISYS_SIP1_IRQ_CTRL_BASE			0x6ed00
#define IPU4P_ISYS_IRQ_MASK_OFFSET			0x04
#define IPU4P_ISYS_IRQ_CLEAR_OFFSET			0x0c
#define IPU4P_ISYS_IRQ_ENABLE_OFFSET			0x10
#define IPU4P_ISYS_IRQ_LEVEL_NOT_PULSE_OFFSET		0x14
#define IPU4P_ISYS_SIP0_IRQ_CTRL_STATUS			0x66d08
#define IPU4P_ISYS_SIP0_IRQ_CTRL_CLEAR			0x66d0c
#define IPU4P_ISYS_SIP1_IRQ_CTRL_STATUS			0x6ed08
#define IPU4P_ISYS_SIP1_IRQ_CTRL_CLEAR			0x6ed0c
#define IPU4P_ISYS_SIP0_CSI2_IRQ			BIT(3)
#define IPU4P_ISYS_SIP1_CSI2_IRQ(port)			BIT((port) - 1)
#define IPU4P_ISYS_SIP1_CSI2_IRQ_MASK			GENMASK(6, 0)

/* ISYS per-port CSI interrupt controls */
#define IPU4P_ISYS_CSI_IRQ_CTRL_BASE(port)		\
	({ typeof(port) __port = (port); \
	   __port ? (0x6cb00 + 0x800 * (__port - 1)) : 0x66300; })
#define IPU4P_ISYS_CSI_IRQ_CTRL0_BASE(port)		\
	({ typeof(port) __port = (port); \
	   __port ? (0x6cc00 + 0x800 * (__port - 1)) : 0x66400; })
#define IPU4P_ISYS_CSI_IRQ_STATUS_OFFSET		0x08
#define IPU4P_ISYS_CSI_IRQ_CLEAR_OFFSET		0x0c
#define IPU4P_ISYS_CSI_IRQ_ACTIVE			BIT(0)
/* CSI-2 frame events occupy bits 16-31 in the shared ctrl0 status. */
#define IPU4P_ISYS_CSI_ERROR_MASK			GENMASK(15, 0)
#define IPU4P_ISYS_CSI_ERROR_BITS			16U

/* IPU4P ISYS GPREG windows */
#define IPU4P_ISYS_GPOFFSET				0x66800
#define IPU4P_ISYS_COMBO_GPOFFSET			0x6e800

/* CSI receiver registers */
#define IPU4P_CSI2_RX_ENABLE				0x00
#define IPU4P_CSI2_RX_ENABLE_ENABLE			BIT(0)
#define IPU4P_CSI2_RX_NOF_ENABLED_LANES			0x04
#define IPU4P_CSI2_RX_CONFIG				0x08
#define IPU4P_CSI2_RX_CONFIG_RELEASE_LP11		BIT(0)
#define IPU4P_CSI2_RX_CONFIG_DISABLE_BYTE_CLK_GATING	BIT(1)
#define IPU4P_CSI2_RX_CONFIG_SKEWCAL_ENABLE		BIT(2)
#define IPU4P_CSI2_RX_HBP_TESTMODE_ENABLE		0x0c
#define IPU4P_CSI2_RX_ERROR_HANDLING			0x10
#define IPU4P_CSI2_RX_SYNC_COUNTER_SEL			0x14
#define IPU4P_CSI2_RX_SYNC_COUNTER_INTERNAL		0
#define IPU4P_CSI2_RX_SYNC_COUNTER_EXTERNAL		3
#define IPU4P_CSI2_RX_SP_IF_CONFIG			0x18
#define IPU4P_CSI2_RX_LP_IF_CONFIG			0x1c
#define IPU4P_CSI2_RX_STATUS				0x20
#define IPU4P_CSI2_RX_STATUS_BUSY			BIT(0)
#define IPU4P_CSI2_RX_STATUS_DLANE_HS			0x24
#define IPU4P_CSI2_RX_STATUS_DLANE_LP			0x28
#define IPU4P_CSI2_RX_DLY_CNT_TERMEN_CLANE		0x2c
#define IPU4P_CSI2_RX_DLY_CNT_SETTLE_CLANE		0x30
#define IPU4P_CSI2_RX_DLY_CNT_TERMEN_DLANE(lane)	(0x34 + (lane) * 8)
#define IPU4P_CSI2_RX_DLY_CNT_SETTLE_DLANE(lane)	(0x38 + (lane) * 8)

/* C-PHY receiver registers */
#define IPU4P_CSI2_RX_CPHY_NOF_ENABLED_LANES		0x04
#define IPU4P_CSI2_RX_CPHY_HBP_TESTMODE			0x08
#define IPU4P_CSI2_RX_CPHY_PH_CRC_CFG			0x0c
#define IPU4P_CSI2_RX_CPHY_ERR_HANDLING			0x10
#define IPU4P_CSI2_RX_CPHY_PORTCFG_CTL			0x14
#define IPU4P_CSI2_RX_CPHY_PORTCFG_TIMEOUT_CNTR	0x18
#define IPU4P_CSI2_RX_CPHY_SYNC_CNTR_SEL		0x1c
#define IPU4P_CSI2_RX_CPHY_STATS			0x20

/* CSI receiver general-purpose registers */
#define IPU4P_CSI2_GPREG_SOFT_RESET			0x00
#define IPU4P_CSI2_GPREG_SOFT_RESET_SLV			0x04
#define IPU4P_CSI2_GPREG_HPLL_FREQ			0x08
#define IPU4P_CSI2_GPREG_ISCLK_RATIO			0x0c
#define IPU4P_CSI2_GPREG_HPLL_FREQ_ISCLK_RATIO_OVERRIDE	0x10
#define IPU4P_CSI2_GPREG_CR_PORT_CONFIG			0x14
#define IPU4P_CSI2_GPREG_RCOMP_TIMER_DISABLE		0x18
#define IPU4P_CSI2_GPREG_RCOMP_TIMER_VALUE		0x1c

/* Per-port interrupt controls */
#define IPU4P_CSI2PART_IRQ_EDGE				0xb00
#define IPU4P_CSI2PART_IRQ_MASK				0xb04
#define IPU4P_CSI2PART_IRQ_STATUS				0xb08
#define IPU4P_CSI2PART_IRQ_CLEAR				0xb0c
#define IPU4P_CSI2PART_IRQ_ENABLE			0xb10
#define IPU4P_CSI2PART_IRQ_LEVEL_NOT_PULSE		0xb14
#define IPU4P_CSI2PART_IRQ_CSIRX			BIT(16)
#define IPU4P_CSI2PART_IRQ_CSI2S2M			BIT(17)

#define IPU4P_CSIRX_IRQ_EDGE				0xc00
#define IPU4P_CSIRX_IRQ_MASK				0xc04
#define IPU4P_CSIRX_IRQ_STATUS				0xc08
#define IPU4P_CSIRX_IRQ_CLEAR				0xc0c
#define IPU4P_CSIRX_IRQ_ENABLE				0xc10
#define IPU4P_CSIRX_IRQ_LEVEL_NOT_PULSE			0xc14
#define IPU4P_CSIRX_ERROR_IRQ_MASK			GENMASK(16, 0)
#define IPU4P_CSIRX_HEADER_SINGLE_ERROR_CORRECTED	BIT(0)
#define IPU4P_CSIRX_HEADER_MULTIPLE_ERRORS_CORRECTED	BIT(1)
#define IPU4P_CSIRX_PAYLOAD_CRC_ERROR			BIT(2)
#define IPU4P_CSIRX_FIFO_OVERFLOW			BIT(3)
#define IPU4P_CSIRX_RESERVED_SHORT_PACKET_DATA_TYPE	BIT(4)
#define IPU4P_CSIRX_RESERVED_LONG_PACKET_DATA_TYPE	BIT(5)
#define IPU4P_CSIRX_INCOMPLETE_LONG_PACKET		BIT(6)
#define IPU4P_CSIRX_FRAME_SYNC_ERROR			BIT(7)
#define IPU4P_CSIRX_LINE_SYNC_ERROR			BIT(8)
#define IPU4P_CSIRX_DPHY_RECOVERABLE_SYNC_ERROR		BIT(9)
#define IPU4P_CSIRX_DPHY_NONRECOVERABLE_SYNC_ERROR	BIT(10)
#define IPU4P_CSIRX_ESCAPE_MODE_ERROR			BIT(11)
#define IPU4P_CSIRX_ESCAPE_MODE_TRIGGER_EVENT		BIT(12)
#define IPU4P_CSIRX_ESCAPE_MODE_ULTRALOW_POWER_DATA	BIT(13)
#define IPU4P_CSIRX_ESCAPE_MODE_ULTRALOW_POWER_EXIT_CLK	BIT(14)
#define IPU4P_CSIRX_INTER_FRAME_SHORT_PACKET_DISCARDED	BIT(15)
#define IPU4P_CSIRX_INTER_FRAME_LONG_PACKET_DISCARDED	BIT(16)
#define IPU4P_CSIRX_NUM_ERRORS				17

#define IPU4P_CSI2S2M_IRQ_EDGE				0xd00
#define IPU4P_CSI2S2M_IRQ_MASK				0xd04
#define IPU4P_CSI2S2M_IRQ_STATUS			0xd08
#define IPU4P_CSI2S2M_IRQ_CLEAR			0xd0c
#define IPU4P_CSI2S2M_IRQ_ENABLE			0xd10
#define IPU4P_CSI2S2M_IRQ_LEVEL_NOT_PULSE		0xd14

#define IPU4P_CSI2_IRQ_FS_VC(vc)			BIT(16 + (vc) * 4)
#define IPU4P_CSI2_IRQ_FE_VC(vc)			BIT(17 + (vc) * 4)
#define IPU4P_CSI2_IRQ_LS_VC(vc)			BIT(18 + (vc) * 4)
#define IPU4P_CSI2_IRQ_LE_VC(vc)			BIT(19 + (vc) * 4)

#define IPU4P_CSI2_CL0_IBUFCTL_EN_FLUSH_FOR_IDRAIN	0x6002c
#define IPU4P_CSI2_CL1_IBUFCTL_EN_FLUSH_FOR_IDRAIN	0x6802c
#define IPU4P_ISYS_IBUFCTL_EN_FLUSH_FOR_IDRAIN		0xb602c

/* PHY sideband registers */
#define IPU4P_CSI2_SB_CSI_RCOMP_CONTROL_LEGACY		0xb8
#define IPU4P_CSI2_SB_CSI_RCOMP_CONTROL_LEGACY_OVR_ENABLE_PORT1_SHIFT 6
#define IPU4P_CSI2_SB_CSI_RCOMP_CONTROL_LEGACY_OVR_ENABLE_PORT2_SHIFT 7
#define IPU4P_CSI2_SB_CSI_RCOMP_CONTROL_LEGACY_OVR_ENABLE_PORT3_SHIFT 8
#define IPU4P_CSI2_SB_CSI_RCOMP_CONTROL_LEGACY_OVR_ENABLE_PORT4_SHIFT 9
#define IPU4P_CSI2_SB_CSI_RCOMP_CONTROL_LEGACY_OVR_CODE_SHIFT 1
#define IPU4P_CSI2_SB_CSI_RCOMP_CONTROL_LEGACY_OVR_ENABLE_SHIFT 0
#define IPU4P_CSI2_SB_CSI_RCOMP_CONTROL_COMBO		0x08
#define IPU4P_CSI2_SB_CSI_RCOMP_UPDATE_MODE_SHIFT	15
#define IPU4P_CSI2_SB_CSI_RCOMP_OVR_ENABLE_SHIFT	6
#define IPU4P_CSI2_SB_CSI_RCOMP_OVR_CODE_SHIFT		1
#define IPU4P_CSI2_SB_CPHY0_DLL_OVRD			0x18
#define IPU4P_CSI2_SB_CPHY0_DLL_OVRD_CRCDC_FSM_DLANE0_SHIFT 1
#define IPU4P_CSI2_SB_CPHY0_DLL_OVRD_LDEN_CRCDC_FSM_DLANE0 BIT(0)
#define IPU4P_CSI2_SB_CPHY2_DLL_OVRD			0x60
#define IPU4P_CSI2_SB_CPHY2_DLL_OVRD_CRCDC_FSM_DLANE1_SHIFT 1
#define IPU4P_CSI2_SB_CPHY2_DLL_OVRD_LDEN_CRCDC_FSM_DLANE1 BIT(0)
#define IPU4P_CSI2_SB_CPHY0_RX_CONTROL1			0x28
#define IPU4P_CSI2_SB_CPHY0_RX_CONTROL1_EQ_LANE0_SHIFT 27
#define IPU4P_CSI2_SB_CPHY2_RX_CONTROL1			0x68
#define IPU4P_CSI2_SB_CPHY2_RX_CONTROL1_EQ_LANE1_SHIFT 27
#define IPU4P_CSI2_SB_DPHY0_DLL_OVRD			0xa4
#define IPU4P_CSI2_SB_DPHY0_DLL_OVRD_LDEN_DRC_FSM_SHIFT 0
#define IPU4P_CSI2_SB_DPHY0_DLL_OVRD_DRC_FSM_OVRD_SHIFT 1
#define IPU4P_CSI2_SB_DPHY1_DLL_OVRD			0xd0
#define IPU4P_CSI2_SB_DPHY1_DLL_OVRD_LDEN_DRC_FSM_SHIFT 0
#define IPU4P_CSI2_SB_DPHY1_DLL_OVRD_DRC_FSM_OVRD_SHIFT 1
#define IPU4P_CSI2_SB_DPHY0_RX_CNTRL			0xb0
#define IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE0_SHIFT 22
#define IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE1_SHIFT 24
#define IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE2_SHIFT 26
#define IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE3_SHIFT 28
#define IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE01_MASK \
	(BIT(IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE0_SHIFT) | \
	 BIT(IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE1_SHIFT))
#define IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE23_MASK \
	(BIT(IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE2_SHIFT) | \
	 BIT(IPU4P_CSI2_SB_DPHY0_RX_CNTRL_SKEWCAL_CR_SEL_DLANE3_SHIFT))

#endif /* IPU4P_ISYS_CSI2_REGS_H */
